[project]
name = "ripper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "typer>=0.21.0",
]

[project.scripts]
# Use a `main` wrapper entrypoint to allow clearer startup logic.
ripper = "ripper.cli:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
